services:
  app:
    build:
      context: .
      dockerfile: .docker/frankenphp/Dockerfile
    container_name: frankenphp-app
    volumes:
      - ./src:/app
      - ./src/vendor:/app/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - SERVER_NAME=:80
#      - FRANKENPHP_CONFIG=worker ./public/frankenphp-worker.php 4
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  db:
    image: mysql:8.0
    container_name: frankenphp-laravel-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network
    ports:
      - "3306:3306"

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
