services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/frankenphp/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./.docker/frankenphp/php.ini:/usr/local/etc/php/99-custom.ini:ro
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
      REDIS_HOST: redis

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: >
      mysqld
      --default-authentication-plugin=mysql_native_password
      --innodb_buffer_pool_size=512M
      --innodb_log_file_size=256M
      --innodb_flush_log_at_trx_commit=2
      --innodb_flush_method=O_DIRECT
      --skip-name-resolve
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

  redis:
    container_name: redis
    image: redis:7.2-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly no --save ""
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
