services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/frankenphp/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app:delegated
      - ./.docker/frankenphp/php.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: frankenphp
      DB_USERNAME: user
      DB_PASSWORD: secret
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      REDIS_PORT: 6379
      OCTANE_WORKERS: 4
      OCTANE_MAX_REQUESTS: 1000
      OCTANE_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: >
      mysqld
      --default-authentication-plugin=mysql_native_password
      --innodb_buffer_pool_size=512M
      --innodb_log_file_size=256M
      --innodb_flush_log_at_trx_commit=2
      --innodb_flush_method=O_DIRECT
      --skip-name-resolve
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
#      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: frankenphp
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    container_name: redis
    image: redis:7.2-alpine
    command: >
      redis-server 
      --maxmemory 256mb 
      --maxmemory-policy allkeys-lru 
      --appendonly yes 
      --appendfsync everysec
      --save ""
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - redis-data:/data
#      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  mysql-data:
  redis-data: